<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hal" nsURI="http://mcgill.ca/emf/examples/hal" nsPrefix="hal">
  <eClassifiers xsi:type="ecore:EClass" name="AutomationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruleId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="precondition" lowerBound="1"
        eType="#//Precondition" eOpposite="#//Precondition/automationrule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//Action" eOpposite="#//Action/automationrule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Precondition" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preconditionId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="automationrule" lowerBound="1"
        eType="#//AutomationRule" eOpposite="#//AutomationRule/precondition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensordevice" eType="#//SensorDevice"
        eOpposite="#//SensorDevice/precondition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlcommand" upperBound="-1"
        eType="#//ControlCommand" eOpposite="#//ControlCommand/action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="automationrule" lowerBound="1"
        eType="#//AutomationRule" eOpposite="#//AutomationRule/action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityLog">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensorreading" upperBound="-1"
        eType="#//SensorReading" eOpposite="#//SensorReading/activitylog"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlcommand" upperBound="-1"
        eType="#//ControlCommand" eOpposite="#//ControlCommand/activitylog"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorReading">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readingValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensorTimestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activitylog" lowerBound="1"
        eType="#//ActivityLog" eOpposite="#//ActivityLog/sensorreading"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensordevice" lowerBound="1"
        eType="#//SensorDevice" eOpposite="#//SensorDevice/sensorreading"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commandId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlTimestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuatordevicetype" lowerBound="1"
        eType="#//ActuatorDeviceType" eOpposite="#//ActuatorDeviceType/controlcommand"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activitylog" lowerBound="1"
        eType="#//ActivityLog" eOpposite="#//ActivityLog/controlcommand"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//Action" eOpposite="#//Action/controlcommand"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorDevice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensordevicetype" lowerBound="1"
        eType="#//SensorDeviceType" eOpposite="#//SensorDeviceType/sensordevice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" lowerBound="1" eType="#//Room"
        eOpposite="#//Room/sensordevice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensorreading" eType="#//SensorReading"
        eOpposite="#//SensorReading/sensordevice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="precondition" eType="#//Precondition"
        eOpposite="#//Precondition/sensordevice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensordevice" upperBound="-1"
        eType="#//SensorDevice" eOpposite="#//SensorDevice/room"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuatordevice" upperBound="-1"
        eType="#//ActuatorDevice" eOpposite="#//ActuatorDevice/room"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActuatorDevice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuatordevicetype" lowerBound="1"
        eType="#//ActuatorDeviceType" eOpposite="#//ActuatorDeviceType/actuatordevice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" lowerBound="1" eType="#//Room"
        eOpposite="#//Room/actuatordevice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorDeviceType" eSuperTypes="#//DeviceType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensordevice" upperBound="-1"
        eType="#//SensorDevice" eOpposite="#//SensorDevice/sensordevicetype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActuatorDeviceType" eSuperTypes="#//DeviceType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuatordevice" upperBound="-1"
        eType="#//ActuatorDevice" eOpposite="#//ActuatorDevice/actuatordevicetype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlcommand" eType="#//ControlCommand"
        eOpposite="#//ControlCommand/actuatordevicetype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Leaf" eSuperTypes="#//Precondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraintValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreconditionComposite" eSuperTypes="#//Precondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="precondition" upperBound="-1"
        eType="#//Precondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bool" eType="#//Logic"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Logic">
    <eLiterals name="AND"/>
    <eLiterals name="OR" value="1"/>
    <eLiterals name="NOT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmartHome">
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" upperBound="-1" eType="#//Room"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="homeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensordevice" upperBound="-1"
        eType="#//SensorDevice" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuatordevice" upperBound="-1"
        eType="#//ActuatorDevice" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceType" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
